import json
P='/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json'
with open(P,'r') as f: L=json.load(f)

# Expand 6.12 Código Inseguro (5 -> 10 steps)
L = [l for l in L if l['filename'] != '6.12-codigo-inseguro.html']
L.extend([
{"filename":"6.12a-codigo-inseguro-memoria.html","module":"6","title":"Falhas de Memória e C (6.12a)","victory_msg":"CÓDIGO INSEGURO DOMINADO!","steps":[
{"type":"teach","icon":"fa-microchip","title":"Corrupção de Memória","content":"Linguagens como C/C++ não gerenciam memória automaticamente. Se o programa gravar dados além do limite de um buffer, ocorre um <b>Buffer Overflow</b>. Isso permite a um atacante injetar e executar código malicioso (shellcode) ou derrubar a aplicação (DoS).","highlight":"Buffer Overflow = sobrescrever memória para ganhar execução de código"},
{"type":"teach","icon":"fa-memory","title":"Memory Leaks","content":"Se um programa aloca memória e esquece de liberá-la, ocorre um <b>Memory Leak</b> (Vazamento de Memória). Com o tempo, o programa consome toda a memória do sistema, resultando em <b>Denial of Service (DoS)</b>.","highlight":"Memory leak = esgotamento de recursos = DoS"},
{"type":"quiz","task":"Uma falha clássica em C/C++ que permite sobrescrever a memória adjacente e possivelmente executar código arbitrário é chamada de:","options":["Buffer Overflow","SQL Injection","Cross-Site Scripting"],"correctText":"Buffer Overflow","explanation":"Buffer overflows exploram a falta de checagem de limites ao escrever dados em variáveis na memória."},
{"type":"teach","icon":"fa-stopwatch","title":"Race Conditions (TOCTOU)","content":"Uma <b>Race Condition</b> ocorre quando o resultado do sistema depende da sequência em que processos são executados. <b>TOCTOU</b> (Time of Check to Time of Use) é quando o estado muda entre a verificação de segurança e o uso real.","highlight":"Condição de corrida = atacar o tempo entre a checagem e a ação"},
{"type":"fill","sentence":"A falha de concorrência onde a segurança é comprometida entre o momento de verificação (Check) e o momento de uso (Use) é chamada de ___.","options":["TOCTOU","XSS","CSRF"],"correctText":"TOCTOU","explanation":"TOCTOU (Time of Check to Time of Use) é um tipo clássico de Race Condition."}
]},
{"filename":"6.12b-codigo-inseguro-web.html","module":"6","title":"Lógica e Deserialização (6.12b)","victory_msg":"DESERIALIZATION DOMINADA!","steps":[
{"type":"teach","icon":"fa-box-open","title":"Insecure Deserialization","content":"Serialização converte objetos em formato salvável/transmissível (JSON, XML, binário). <b>Deserialização</b> reconstrói o objeto. Se a aplicação deserializar dados fornecidos pelo usuário sem validação, o atacante pode instanciar classes maliciosas e obter <b>RCE</b> (Remote Code Execution).","highlight":"Nunca deserialize dados não confiáveis!"},
{"type":"example","icon":"fa-terminal","title":"Deserialização em PHP","scenario":"A aplicação recebe um cookie serializado do usuário e o deserializa. O atacante forja um objeto malicioso para executar comandos na criação.","code":"// Código vulnerável\n$user = unserialize($_COOKIE['user_data']);","takeaway":"Use formatos seguros (JSON) sem instanciar classes ativamente se não for estritamente necessário."},
{"type":"teach","icon":"fa-code-compare","title":"Tratamento de Erros Inseguro","content":"Erros devem ser tratados com cuidado. Falhar 'aberto' (fail open) pode ignorar controles de segurança se ocorrer um erro. O correto é <b>fail close</b> (falhar fechado), negando o acesso por padrão em caso de erro. Expor stack traces (A05) também vaza dados.","highlight":"Em caso de erro, a resposta padrão deve ser 'Acesso Negado'"},
{"type":"quiz","task":"Qual prática de desenvolvimento seguro determina que, em caso de exceção ou erro no sistema, o acesso deve ser negado por padrão?","options":["Fail Close","Fail Open","Race Condition"],"correctText":"Fail Close","explanation":"Fail close (ou fail secure) garante que uma falha não resulte em bypass de segurança."},
{"type":"match","title":"Falha de Código → Descrição","pairs":[{"term":"Buffer Overflow","definition":"Sobrescreve a memória adjacente"},{"term":"Insecure Deserialization","definition":"Reconstrói objetos perigosos a partir de input"},{"term":"Race Condition","definition":"Explora a concorrência e timing"},{"term":"Memory Leak","definition":"Esquece de liberar memória, causando DoS"}]}
]}
])

# Expand 8.1 and 8.2 (Post exploitation and Lateral Movement)
L = [l for l in L if l['filename'] != '8.1-persistencia.html' and l['filename'] != '8.2-lateral-evasao.html']
L.extend([
{"filename":"8.1a-persistencia-avancada.html","module":"8","title":"Persistência Avançada 8.1a","victory_msg":"PERSISTÊNCIA AVANÇADA DOMINADA!","steps":[
{"type":"teach","icon":"fa-anchor","title":"Persistência no Windows","content":"Além de scheduled tasks e contas locais, atacantes mantêm acesso via: <b>Registry Run Keys</b> (executa na inicialização), <b>Serviços do Windows</b> (executa como SYSTEM), <b>WMI Event Subscriptions</b> (executa payloads em resposta a eventos do sistema) e <b>Sticky Keys</b> (acesso via login screen).","highlight":"Persistência = sobreviver a reboots"},
{"type":"teach","icon":"fa-linux","title":"Persistência no Linux","content":"No Linux, a persistência é feita via: chaves <b>SSH</b> em ~/.ssh/authorized_keys, <b>Cron jobs</b>, <b>Serviços systemd</b> e arquivos de inicialização do bash (<b>.bashrc</b>, <b>.profile</b>).","highlight":"Um SSH key garante acesso invisível e permanente"},
{"type":"example","icon":"fa-terminal","title":"Backdoor via .bashrc","scenario":"O atacante adiciona um alias no .bashrc do root. Toda vez que o root digita 'ls', um script malicioso é executado silenciosamente.","code":"echo \"alias ls='ls --color=auto; /tmp/backdoor.sh'\" >> ~/.bashrc","takeaway":"Isso permite roubar senhas de sudo quando o admin usa o terminal."},
{"type":"quiz","task":"Qual técnica de persistência do Windows permite que payloads sejam executados em resposta a eventos do sistema operacional, sem arquivos no disco?","options":["WMI Event Subscriptions","Sticky Keys","Cron jobs"],"correctText":"WMI Event Subscriptions","explanation":"WMI (Windows Management Instrumentation) permite disparar scripts quando certos eventos (ex: login de usuário) ocorrem."},
{"type":"fill","sentence":"A técnica de persistência que explora ferramentas de acessibilidade do Windows na tela de login é chamada de ___.","options":["Sticky Keys","Run Keys","WMI"],"correctText":"Sticky Keys","explanation":"O ataque Sticky Keys substitui o utilitário sethc.exe (acionado por Shift 5 vezes) por cmd.exe na tela de login."}
]},
{"filename":"8.2a-lateral-exfiltracao.html","module":"8","title":"Mov. Lateral e Exfiltração 8.2a","victory_msg":"MOVIMENTO LATERAL E EXFILTRAÇÃO DOMINADOS!","steps":[
{"type":"teach","icon":"fa-arrows-left-right","title":"Movimento Lateral: Execução","content":"Após obter um hash (Pass-the-Hash) ou ticket (Pass-the-Ticket), o atacante precisa executar comandos remotamente. Ferramentas: <b>PsExec</b> (via SMB), <b>WMIExec</b>, <b>WinRM</b> (Powershell Remoting).","highlight":"Mover-se = autenticar e executar código noutro host"},
{"type":"teach","icon":"fa-upload","title":"Exfiltração de Dados","content":"O objetivo final muitas vezes é roubar dados (Exfiltração). Para não ser pego pelo firewall/DLP, o atacante usa canais encobertos: <b>DNS Tunneling</b>, ICMP, HTTPS, ou esteganografia.","highlight":"Exfiltração = tirar o prêmio de dentro da rede"},
{"type":"example","icon":"fa-terminal","title":"DNS Tunneling","scenario":"O atacante encoda dados em base64 e os envia como subdomínios em requisições DNS para o servidor do atacante.","code":"# Vítima tenta resolver:\ndados-secretos-base64.atacante.com\n\n# O servidor DNS do atacante recebe e decoda os dados","takeaway":"O tráfego DNS raramente é bloqueado ou inspecionado a fundo por firewalls corporativos."},
{"type":"teach","icon":"fa-user-ninja","title":"Cobalt Strike e C2","content":"Atores avançados (APTs e Ransomware) usam <b>Cobalt Strike</b> para movimentação lateral e evasão. Ele possui <b>Malleable C2</b>, que permite alterar a assinatura do tráfego para parecer com navegação web normal (Amazon, Gmail) e enganar o IDS/IPS.","highlight":"Cobalt Strike = padrão ouro do malware avançado"},
{"type":"match","title":"Fase Pós-Exploração → Ferramenta/Técnica","pairs":[{"term":"Execução Remota","definition":"PsExec, WMIExec"},{"term":"Evasão de IDS/IPS","definition":"Malleable C2, Obfuscation"},{"term":"Persistência (Win)","definition":"Registry Run Keys, WMI"},{"term":"Exfiltração","definition":"DNS Tunneling"}]},
{"type":"quiz","task":"Qual ferramenta/tecnologia é usada em ataques de exfiltração para esconder dados enviados para fora da rede, passando por firewalls restritivos?","options":["DNS Tunneling","Nmap","Enum4linux"],"correctText":"DNS Tunneling","explanation":"DNS Tunneling usa requisições de resolução de nomes comuns para extrair ou receber dados sorrateiramente."}
]}
])

with open(P,'w') as f: json.dump(L,f,ensure_ascii=False,indent=2)
print(f"✅ {len(L)} lessons (expanded 6.12, 8.1, 8.2)")
