import json
with open('/home/gabriel/Documentos/dev/cyberduo/scripts/lesson_definitions.json','r') as f: lessons=json.load(f)
lessons.extend([
{"filename":"8.0-introducao.html","module":"8","title":"Pós-Exploração 8.0","victory_msg":"PÓS-EXPLORAÇÃO INICIADA!","steps":[
{"type":"teach","icon":"fa-door-open","title":"Pós-Exploração","content":"Após comprometer um sistema, o atacante precisa <b>manter acesso</b> (persistência), <b>mover-se lateralmente</b> pela rede e <b>evitar detecção</b>.","highlight":"Entrar é só o começo"},
{"type":"teach","icon":"fa-unlock","title":"Escalação de Privilégios","content":"<b>Privilege Escalation</b>: passar de usuário comum para <b>root/admin</b>. Pode ser <b>vertical</b> (user→admin) ou <b>horizontal</b> (user→outro user).","highlight":"Sem privilégios = acesso limitado"},
{"type":"quiz","task":"Qual tipo de escalação de privilégios passa de usuário comum para administrador?","options":["Vertical","Horizontal","Lateral"],"correctText":"Vertical","explanation":"Vertical = subir de nível (user→admin). Horizontal = mesmo nível, outra conta."},
{"type":"fill","sentence":"A escalação ___ de privilégios ocorre quando um usuário comum obtém acesso de root/admin.","options":["vertical","horizontal","diagonal"],"correctText":"vertical","explanation":"Vertical = subir de nível de permissão no mesmo sistema."}
]},
{"filename":"8.1-persistencia.html","module":"8","title":"Persistência 8.1","victory_msg":"PERSISTÊNCIA DOMINADA!","steps":[
{"type":"teach","icon":"fa-anchor","title":"Manutenção de Acesso","content":"<b>Persistência</b> garante que o atacante não perca acesso após reboot ou detecção. Técnicas: <b>backdoors</b>, <b>web shells</b>, <b>scheduled tasks</b>, <b>rootkits</b> e <b>criação de contas</b>.","highlight":"Persistência = acesso permanente"},
{"type":"teach","icon":"fa-terminal","title":"Web Shells","content":"Uma <b>web shell</b> é um script (PHP, ASP) no servidor web que permite executar comandos remotamente pelo browser. É a forma mais simples de manter acesso.","highlight":"Web shell = terminal via browser"},
{"type":"example","icon":"fa-code","title":"Web Shell PHP","scenario":"O atacante faz upload de um arquivo PHP malicioso que executa comandos do sistema operacional via parâmetro GET.","code":"<?php system($_GET['cmd']); ?>\n// Acesso: http://alvo.com/shell.php?cmd=whoami","takeaway":"Web shells são difíceis de detectar se bem escondidas."},
{"type":"quiz","task":"Qual técnica permite manter acesso remoto a um servidor web através do browser?","options":["Web Shell","SQL Injection","Phishing"],"correctText":"Web Shell","explanation":"Web shells são scripts no servidor que permitem execução remota de comandos."},
{"type":"teach","icon":"fa-ghost","title":"Rootkits","content":"<b>Rootkits</b> operam no nível do kernel, escondendo processos, arquivos e conexões do sistema operacional. São extremamente difíceis de detectar e remover.","highlight":"Rootkit = invisibilidade total"},
{"type":"match","title":"Técnica → Descrição","pairs":[{"term":"Web Shell","definition":"Script web para comandos remotos"},{"term":"Rootkit","definition":"Se esconde no kernel do SO"},{"term":"Scheduled Task","definition":"Executa payload periodicamente"},{"term":"Backdoor SSH","definition":"Chave SSH adicionada ao authorized_keys"}]},
{"type":"fill","sentence":"Um ___ opera no nível do kernel, tornando-se praticamente invisível para o sistema operacional.","options":["rootkit","firewall","antivírus"],"correctText":"rootkit","explanation":"Rootkits se integram ao kernel, ocultando toda atividade maliciosa."}
]},
{"filename":"8.2-lateral-evasao.html","module":"8","title":"Movimento Lateral 8.2","victory_msg":"LATERAL MOVEMENT DOMINADO!","steps":[
{"type":"teach","icon":"fa-arrows-left-right","title":"Movimento Lateral","content":"<b>Movimento lateral</b> é mover-se de um sistema comprometido para outros na rede. Usa credenciais capturadas, hashes (Pass-the-Hash) ou tokens (Pass-the-Ticket).","highlight":"Um sistema comprometido abre caminho para todos"},
{"type":"teach","icon":"fa-key","title":"Pass-the-Ticket (Kerberos)","content":"Em redes <b>Active Directory</b>, o atacante captura <b>Kerberos tickets</b> (TGT/TGS) e os usa para autenticar em outros serviços sem precisar da senha.","highlight":"Kerberos ticket = passe livre pela rede AD"},
{"type":"teach","icon":"fa-eye-slash","title":"Evasão de Detecção","content":"Técnicas de evasão: <b>Living off the Land</b> (usar ferramentas do próprio SO), <b>ofuscação</b> de payloads, <b>timestomping</b> (alterar datas de arquivos), <b>log clearing</b>.","highlight":"Usar ferramentas do SO evita alertas de antivírus"},
{"type":"quiz","task":"O que é 'Living off the Land'?","options":["Usar ferramentas nativas do SO para evitar detecção","Instalar malware personalizado no alvo","Enviar phishing para todos os funcionários"],"correctText":"Usar ferramentas nativas do SO para evitar detecção","explanation":"LOLBins (Living off the Land Binaries) são ferramentas legítimas do SO usadas para fins maliciosos."},
{"type":"example","icon":"fa-terminal","title":"PowerShell como LOLBin","scenario":"O atacante usa <b>PowerShell</b> (ferramenta legítima do Windows) para baixar e executar payloads. O antivírus não bloqueia pois PowerShell é um programa confiável.","code":"powershell -ep bypass -e [BASE64_PAYLOAD]","takeaway":"PowerShell é a ferramenta LOLBin mais usada em ataques Windows."},
{"type":"match","title":"Evasão → Técnica","pairs":[{"term":"LOLBins","definition":"Ferramentas legítimas do SO"},{"term":"Timestomping","definition":"Alterar datas de arquivos"},{"term":"Log Clearing","definition":"Apagar registros de atividade"}]},
{"type":"fill","sentence":"A técnica de alterar timestamps de arquivos maliciosos para parecerem legítimos é o ___.","options":["timestomping","phishing","spoofing"],"correctText":"timestomping","explanation":"Timestomping modifica datas de criação/modificação para dificultar análise forense."}
]}
])
with open('/home/gabriel/Documentos/dev/cyberduo/scripts/lesson_definitions.json','w') as f: json.dump(lessons,f,ensure_ascii=False,indent=2)
print(f"✅ {len(lessons)} lessons (added Module 8)")
