import json
with open('/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json','r') as f: lessons=json.load(f)
lessons.extend([
{"filename":"9.0-introducao.html","module":"9","title":"Relatórios 9.0","victory_msg":"RELATÓRIOS INICIADOS!","steps":[
{"type":"teach","icon":"fa-file-alt","title":"A Importância do Relatório","content":"O relatório é o <b>produto final</b> do pentest. Um relatório mal escrito invalida todo o trabalho técnico. Deve ser claro para <b>executivos</b> e detalhado para <b>técnicos</b>.","highlight":"Relatório ruim = pentest inútil"},
{"type":"teach","icon":"fa-users","title":"Dois Públicos","content":"O relatório tem duas seções: <b>Executive Summary</b> (para gestão, sem jargão técnico) e <b>Technical Details</b> (para equipe técnica, com evidências e reprodução).","highlight":"Fale a língua do seu público"},
{"type":"quiz","task":"Qual é o produto final mais importante de um pentest?","options":["O relatório escrito","As ferramentas usadas","O número de vulnerabilidades"],"correctText":"O relatório escrito","explanation":"Sem relatório claro, o cliente não consegue corrigir as vulnerabilidades."},
{"type":"fill","sentence":"O relatório deve ter um ___ para executivos e detalhes técnicos para a equipe de TI.","options":["Executive Summary","código-fonte","payload"],"correctText":"Executive Summary","explanation":"Executive Summary traduz achados técnicos em riscos de negócio."}
]},
{"filename":"9.1-componentes-relatorio.html","module":"9","title":"Componentes do Relatório 9.1","victory_msg":"ESTRUTURA DO RELATÓRIO DOMINADA!","steps":[
{"type":"teach","icon":"fa-list","title":"Estrutura do Relatório","content":"Componentes essenciais: <b>Escopo</b>, <b>Metodologia</b>, <b>Executive Summary</b>, <b>Achados</b> (com CVSS), <b>Evidências</b> (screenshots), <b>Recomendações</b> e <b>Anexos</b>.","highlight":"Estrutura padronizada garante completude"},
{"type":"teach","icon":"fa-camera","title":"Evidências","content":"Cada vulnerabilidade deve ter <b>evidência reproduzível</b>: screenshots, logs, requests/responses do Burp, e passos exatos para reproduzir. Sem evidência = achado descartável.","highlight":"Evidência concreta é incontestável"},
{"type":"teach","icon":"fa-chart-pie","title":"Classificação de Risco","content":"Cada achado recebe uma classificação: <b>Crítico</b>, <b>Alto</b>, <b>Médio</b>, <b>Baixo</b>, <b>Informativo</b>. Baseada no <b>CVSS</b> e no <b>contexto de negócio</b> do cliente.","highlight":"Contexto de negócio afeta a classificação"},
{"type":"match","title":"Seção → Conteúdo","pairs":[{"term":"Executive Summary","definition":"Visão geral para gestão"},{"term":"Achados","definition":"Vulnerabilidades com CVSS e evidências"},{"term":"Recomendações","definition":"Como corrigir cada vulnerabilidade"},{"term":"Metodologia","definition":"Frameworks e ferramentas usadas"}]},
{"type":"quiz","task":"O que torna uma evidência de vulnerabilidade válida no relatório?","options":["Screenshots e passos reproduzíveis","Apenas a opinião do pentester","O nome da ferramenta que detectou"],"correctText":"Screenshots e passos reproduzíveis","explanation":"Evidência deve permitir que outro profissional reproduza o achado."},
{"type":"fill","sentence":"Cada vulnerabilidade deve incluir uma pontuação ___ para indicar sua gravidade.","options":["CVSS","DNS","TCP"],"correctText":"CVSS","explanation":"CVSS padroniza a gravidade das vulnerabilidades de 0 a 10."}
]},
{"filename":"9.2-analise-recomendacoes.html","module":"9","title":"Análise e Recomendações 9.2","victory_msg":"RECOMENDAÇÕES FORMULADAS!","steps":[
{"type":"teach","icon":"fa-wrench","title":"Recomendações de Correção","content":"Cada achado deve ter uma <b>recomendação específica</b>: não apenas 'corrigir SQLi', mas sim 'implementar Prepared Statements na query X do arquivo Y, linha Z'.","highlight":"Recomendações vagas são inúteis"},
{"type":"teach","icon":"fa-sort-amount-up","title":"Priorização","content":"Priorize correções por: <b>CVSS</b> (gravidade), <b>exposição</b> (internet vs interna), <b>facilidade de exploração</b> e <b>impacto no negócio</b>.","highlight":"Corrija o mais perigoso primeiro"},
{"type":"example","icon":"fa-list-ol","title":"Priorizando Achados","scenario":"SQLi no login público (CVSS 9.8, internet) > XSS no painel admin interno (CVSS 6.1, intranet) > Versão de jQuery desatualizada (CVSS 3.1, informativo).","takeaway":"Exposição e impacto pesam tanto quanto o CVSS."},
{"type":"quiz","task":"Como deve ser uma boa recomendação de correção?","options":["Específica: arquivo, linha e correção exata","Genérica: 'melhore a segurança'","Apenas o link do CVE"],"correctText":"Específica: arquivo, linha e correção exata","explanation":"Recomendações específicas permitem que a equipe técnica corrija rapidamente."},
{"type":"fill","sentence":"A priorização deve considerar CVSS, exposição e ___ no negócio.","options":["impacto","cor","tamanho"],"correctText":"impacto","explanation":"Impacto no negócio determina a urgência real da correção."}
]},
{"filename":"9.3-comunicacao-escalonamento.html","module":"9","title":"Comunicação 9.3","victory_msg":"COMUNICAÇÃO PROFISSIONAL DOMINADA!","steps":[
{"type":"teach","icon":"fa-bullhorn","title":"Comunicação Durante o Teste","content":"O pentester deve manter <b>comunicação constante</b> com o ponto de contato. Achados <b>críticos</b> devem ser reportados <b>imediatamente</b>, não esperar o relatório final.","highlight":"Achado crítico = reporte imediato"},
{"type":"teach","icon":"fa-triangle-exclamation","title":"Escalonamento","content":"Se durante o teste o pentester encontrar <b>evidência de invasão real</b> (não simulada), deve <b>parar</b> e <b>escalar</b> imediatamente para a equipe de resposta a incidentes.","highlight":"Invasão real ≠ teste. Pare e escale."},
{"type":"quiz","task":"O que fazer ao encontrar evidência de invasão real durante um pentest?","options":["Parar e escalar para resposta a incidentes","Continuar o teste normalmente","Tentar remover o invasor por conta própria"],"correctText":"Parar e escalar para resposta a incidentes","explanation":"Evidência de comprometimento real exige resposta a incidentes, não continuação do teste."},
{"type":"fill","sentence":"Achados de severidade ___ devem ser reportados imediatamente, sem esperar o relatório final.","options":["crítica","baixa","informativa"],"correctText":"crítica","explanation":"Vulnerabilidades críticas representam risco iminente e exigem ação imediata."}
]},
{"filename":"9.4-atividades-pos-entrega.html","module":"9","title":"Pós-Entrega 9.4","victory_msg":"PÓS-ENTREGA CONCLUÍDA!","steps":[
{"type":"teach","icon":"fa-broom","title":"Limpeza Pós-Teste","content":"Após o teste, o pentester deve <b>remover</b> todos os artefatos: <b>web shells</b>, <b>contas criadas</b>, <b>backdoors</b>, <b>arquivos temporários</b>. Deixar restos é irresponsável.","highlight":"Limpe tudo que você criou durante o teste"},
{"type":"teach","icon":"fa-handshake","title":"Debriefing","content":"O <b>debriefing</b> é a reunião pós-entrega onde o pentester apresenta os achados, responde dúvidas e ajuda a equipe técnica a entender as recomendações.","highlight":"Debriefing garante que as correções serão feitas"},
{"type":"teach","icon":"fa-rotate-right","title":"Retest","content":"Após o cliente corrigir as vulnerabilidades, o pentester realiza um <b>retest</b> para verificar se as correções foram eficazes e não introduziram novos problemas.","highlight":"Retest confirma que as correções funcionaram"},
{"type":"quiz","task":"O que o pentester deve fazer com web shells e backdoors após o teste?","options":["Remover todos completamente","Deixar para futuras referências","Compartilhar com colegas"],"correctText":"Remover todos completamente","explanation":"Artefatos deixados no sistema são uma vulnerabilidade real que poderia ser explorada."},
{"type":"match","title":"Atividade → Momento","pairs":[{"term":"Limpeza de artefatos","definition":"Imediatamente após o teste"},{"term":"Debriefing","definition":"Após entrega do relatório"},{"term":"Retest","definition":"Após o cliente corrigir os achados"}]},
{"type":"fill","sentence":"A reunião onde o pentester apresenta os achados ao cliente é chamada de ___.","options":["debriefing","kickoff","standup"],"correctText":"debriefing","explanation":"Debriefing é a sessão final de apresentação e discussão dos resultados."}
]}
])
with open('/home/gabriel/Downloads/64Gram Desktop/CyberDuo/scripts/lesson_definitions.json','w') as f: json.dump(lessons,f,ensure_ascii=False,indent=2)
print(f"✅ {len(lessons)} lessons (added Module 9)")
